spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/fixitnow?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=11@Avningalgi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
